# Generated by Django 4.2 on 2023-05-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productor",
            name="cedula",
            field=models.CharField(max_length=40, unique=True, verbose_name="Cedula"),
        ),
    ]
