# Generated by Django 4.2 on 2023-05-30 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("productor", "0002_alter_productor_cedula"),
    ]

    operations = [
        migrations.CreateModel(
            name="Finca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=150, verbose_name="Nombre Finca"),
                ),
                (
                    "direccion",
                    models.CharField(max_length=150, verbose_name="Direccion Finca"),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="Editado"),
                ),
                (
                    "productor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productor.productor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Finca",
                "verbose_name_plural": "Fincas",
            },
        ),
    ]
