# Generated by Django 4.2 on 2023-05-30 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("productor", "0002_alter_productor_cedula"),
        ("recolector", "0001_initial"),
        ("finca", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recoleccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField(verbose_name="Cantidad de leche")),
                ("novedad", models.CharField(max_length=250, verbose_name="novedad")),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="Editado"),
                ),
                (
                    "finca",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finca.finca",
                    ),
                ),
                (
                    "productor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productor.productor",
                    ),
                ),
                (
                    "recolector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recolector.recolector",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recoleccion",
                "verbose_name_plural": "Recolecciones",
            },
        ),
    ]
